# Generated by Django 5.2.8 on 2025-11-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_category'),
    ]

    operations = [
    ]
